module.exports = {
  "66 Place": "96",
  "Allison Recreation Fields, Betty and Bobby": "52",
  "Art and Design Gallery": "4",
  "Art Annex": "3",
  "Baker Bookstore": "5",
  "Baker Observatory": "98",
  "Bears' Den": "334",
  "Bikerack": "264",
  "Bikeways": "263",
  "Blair-Shannon House": "7",
  "Bond Learning Center": "301",
  "Brick City": "140",
  "Bull Shoals Field Station": "97",
  "Burgess House": "8",
  "Carrington Hall": "9",
  "Central Stores and Maintenance": "10",
  "Cheek Hall": "11",
  "Cherry Hall": "18",
  "Child Development Center": "12",
  "Clay Hall": "56",
  "Corral": "88",
  "Craig Hall": "13",
  "Craig Hall Plaza (Tent Pad)": "83",
  "Crowder College": "276",
  "Crowder College - Cassville Campus": "330",
  "Custodial Offices": "14",
  "Darr Agricultural Center": "99",
  "Dogwood Apartments": "15",
  "Early Childhood &amp; Family Development Center": "72",
  "Ellis Hall": "16",
  "Farber Building": "259",
  "Field Hockey and Lacrosse": "365",
  "Forsythe Athletics Center": "19",
  "Foster Recreation Center, Bill R. and Family": "302",
  "Freudenberger House": "20",
  "Garst Dining Center": "77",
  "Glass Hall, David D.": "21",
  "Grand Street Underpass": "22",
  "Great Southern Building": "101",
  "Greenwood Laboratory School": "23",
  "Hammons Hall for the Performing Arts, Juanita K.": "31",
  "Hammons House": "25",
  "Hammons Student Center, John Q.": "26",
  "Hill Hall": "27",
  "Historic Quadrangle": "87",
  "Hutchens House": "45",
  "Intramural Sports Field": "80",
  "Joplin Graduate Center": "291",
  "Joplin High School Media Center": "292",
  "Jordan Valley Innovation Center, Roy Blunt": "102",
  "JQH Arena": "136",
  "JVIC Labs": "254",
  "Karls Hall": "33",
  "Kelsey Norman Elementary School": "293",
  "Kemper Hall": "34",
  "Kentwood Hall": "35",
  "Kentwood South Apartments": "36",
  "Kings Street": "89",
  "Kings Street Annex": "37",
  "Kraft Administration Center": "290",
  "KSMU Radio Station": "32",
  "Levy/Wolf Building": "81",
  "Madison Hall": "38",
  "Mallory Plaza, Arthur L.": "130",
  "McDonald Arena Patio": "91",
  "McDonald Hall &amp; Arena": "39",
  "McQueary Family Health Sciences Hall": "46",
  "Memorial Garden": "131",
  "Meyer Alumni Center, Kenneth E.": "1",
  "Meyer Carillon, Jane A.": "132",
  "Meyer Library, Duane G.": "40",
  "Missouri State University - Joplin Campus": "272",
  "Missouri State University - Nevada Campus": "304",
  "Monroe Apartments": "337",
  "Monroe Hall": "41",
  "Morris Center, Jim D.": "30",
  "Nelson Education Center": "274",
  "Nevada TeleCenter": "278",
  "Nevada Telecenter": "257",
  "North Mall": "82",
  "Northeastern Oklahoma A&amp;M": "280",
  "One-Room School House": "133",
  "Park Central Office Building": "94",
  "Pinegar Arena": "270",
  "Plaster Center for Free Enterprise and Business Development, Robert W.": "262",
  "Plaster Stadium, Robert W.": "53",
  "Plaster Student Union, Robert W.": "54",
  "Power House": "48",
  "Price Plaza": "134",
  "Professional Building": "49",
  "Pummill Hall": "51",
  "Redlands Community College": "285",
  "Retreat Garden": "135",
  "Safety and Transportation Booth North": "100",
  "Safety and Transportation Booth South": "55",
  "Safety and Transportation Offices/Police Substation": "75",
  "Sand Volleyball": "364",
  "Scholars House": "71",
  "Siceluff Hall": "57",
  "Soccer and Track": "363",
  "Soccer Field": "58",
  "Softball Field": "59",
  "Strong Hall": "50",
  "Student Exhibition Center": "60",
  "Sunvilla Tower": "61",
  "Taylor Health and Wellness Center": "62",
  "Temple Hall": "63",
  "Tennis Courts": "64",
  "Theatre and Dance Annex": "127",
  "Transit Operations Center": "66",
  "Trottier Plaza": "90",
  "University Hall": "67",
  "Warren Center for Archaeological Research, Bernice": "2",
  "Waynesville Central Office": "288",
  "Wehr Band Hall": "68",
  "Wells House": "69",
  "West Mall (Amphitheatre)": "92",
  "West Mall (Carrington)": "93",
  "West Mall (Fountain)": "24",
  "Williams Building": "260",
  "Woodruff Building": "124",
  "Woods House": "70"
}
