r = {
  "A Cub Bella (ACB)": "St355",
  "Academic Achievement Center, Dr. Mary Jo Wynn (formerly Achievement Center for Interc": "De156",
  "Academic Advisement Center": "De50",
  "Academic Integrity": "Su233",
  "Academic Integrity Matters Student Organization (AIM SO)": "St936",
  "Academic Media Production Guild (AMPG)": "St977",
  "Academy for Educational Studies": "Su817",
  "Access Technology Center": "Su35",
  "Accountancy, School of": "De51",
  "Accounting Club/Institute of Management Accountants Student Chapter (Accounting Club/": "St168",
  "Administrative and Information Services Division": "De136",
  "Administrative Studies Program, Master of Science in": "De186",
  "Admissions, Office of": "De137",
  "Adolos  (Adolos)": "St94",
  "Adult Student Services": "De80",
  "Advertising Club (AD CLUB)": "St144",
  "Advertising Team": "Su952",
  "Advocates": "St978",
  "Advocating for Families and Children (MoStateAFC)": "St979",
  "Aerialists (MSU Aerialists)": "St980",
  "African American Studies Program": "De163",
  "African Student Association (ASA)": "St1004",
  "Agronomy Club": "St145",
  "Alliance for Veterans": "Su813",
  "Alpha Chi Omega (Alpha Chi)": "St138",
  "Alpha Delta Mu, Beta Omicron Chapter": "St749",
  "Alpha Delta Pi  (ADPi)": "St170",
  "Alpha Gamma Rho (Ag Rho)": "St171",
  "Alpha Gamma Sigma Fraternity (Ag Sig)": "St122",
  "Alpha Kappa Lambda (AKL)": "St90",
  "Alpha Kappa Psi (AKPsi)": "St28",
  "Alpha Phi Alpha Fraternity, Inc.": "St616",
  "Alpha Phi Omega (APO)": "St88",
  "Alpha Phi Sigma-Sigma Mu Sigma": "St818",
  "Alpha Sigma Alpha (ASA)": "St91",
  "Alpha Sigma Lambda": "St172",
  "Alumni Association": "De53",
  "American Chemical Society (ACS)": "St174",
  "American Fisheries Society Subunit (AFS Subunit)": "St928",
  "American Indian Student Association (A.I.S.A.)": "St216",
  "American Society for Photogrammetry and Remote Sensing (ASPRS) (ASPRS)": "St890",
  "American Society of Interior Designers (ASID)": "St589",
  "Anthropology Club (Anthro Club)": "St125",
  "Anthropology Program": "Su774",
  "Applied Anthropology Graduate Student Association (AAGSA)": "St1005",
  "Applied Science and Engineering, Center for": "De273",
  "Archaeological Research, Center for": "De138",
  "Archery Club": "St1006",
  "Area Health Education Center, Southwest Missouri": "De209",
  "Art and Design Department": "De54",
  "Art Club": "St588",
  "Art History Club": "St840",
  "Arts and Letters, College of": "De14",
  "Arts in the Schools, Center for": "De341",
  "Asian American Pacific Islander Organization": "St528",
  "Asian Studies Program": "De224",
  "Assessment, Office of": "De60",
  "Associated Builders and Contractors (ABC)": "St1007",
  "Association for Computing Machinery (ACM)": "St182",
  "Association for Women in Communication Plus (AWC+)": "St955",
  "Association of Black Collegians (ABC)": "St92",
  "Association of Fashion and Design (aFAD)": "St762",
  "Association of Fundraising Professionals (AFP)": "St929",
  "Association of Information Technology Professionals (AITP)": "St582",
  "Association of International Students (AIS)": "St103",
  "Association of Student Physical Therapists (ASPT)": "St187",
  "Athletic Medical and Rehabilitation Services": "De366",
  "Athletic Training Students Association (ATSA)": "St86",
  "Athletics Communications": "De354",
  "Athletics Compliance, Office of": "De380",
  "Athletics Development": "De409",
  "Athletics, Intercollegiate": "De55",
  "Audiology, Doctorate of": "De225",
  "Bands": "Su537",
  "Bear Breaks": "St893",
  "Bear CLAW (Center for Learning and Writing)": "De367",
  "Bear Service Team": "St867",
  "BearConnect": "St894",
  "BearPass Card Office": "De133",
  "Bears for Life: MSU Pro-Life Advocates (Bears for Life)": "St710",
  "Beartones (BTZ)": "St104",
  "Beta Alpha Psi, Business Information Fraternity": "St191",
  "Beta Beta Beta Biological Honor Society (Tri-Beta)": "St192",
  "Biology Department": "De56",
  "Biomedical and Life Sciences, Center for (CBLS)": "De335",
  "Biomedical Sciences Department": "De57",
  "Black Bear, The": "St1008",
  "Blair-Shannon House": "St920",
  "Block &amp; Bridle  (Block and Bridle)": "St962",
  "Blunt Jordan Valley Innovation Center, Roy (JVIC)": "De334",
  "Board of Governors": "De26",
  "Bookstore": "De177",
  "Boomerang Squad (B-Squad)": "St1009",
  "Boxing Team (MSU Boxing Team)": "St1010",
  "Brass Society": "St998",
  "Brick City Gallery": "De378",
  "Broadcast Services": "De215",
  "Bull Shoals Field Station": "De337",
  "Bursar's Office": "De58",
  "Business Administration, Master of": "Su867",
  "Business Advisement Center": "De147",
  "Business Incubator": "De401",
  "Business, College of": "De12",
  "Campus 4 Christ (C4C)": "St967",
  "Campus Judicial Board": "Su794",
  "Campus Recreation": "De176",
  "Canterbury Club (Episcopal Campus Ministry )": "St956",
  "Career Center": "De59",
  "Catholic Campus Ministry (CCM)": "St657",
  "Cattlemen's Association (MSU Cattlemen's Association)": "St1001",
  "CBCO Blood Drive Recruitment Team": "St819",
  "Cell and Molecular Biology Society (CMB Society)": "St869",
  "Chemistry Department": "De64",
  "Chess Club": "St619",
  "Chi Alpha Christian Fellowship (XA)": "St98",
  "Chi Rho (Greek Ministry)": "St952",
  "Chi Sigma Alpha National Student Affairs Honor Fraternity (Chi Sigma Alpha)": "St957",
  "Child Development Center": "De269",
  "Child Life Student Association (C.L.S.A.)": "St737",
  "Childhood Education and Family Studies, Department of": "De346",
  "China Programs": "Su485",
  "Chinese Student Christian Association": "St841",
  "Chinese Students and Scholars Association (CSSA)": "St821",
  "Choral Studies Executive Board": "St1011",
  "Christian Campus House (CCH)": "St99",
  "Christian Student Center (CSC)": "St116",
  "Christians In Action (CIA - Springfield)": "St958",
  "Citizenship and Service-Learning (CASL)": "De65",
  "Clarinet Society of Missouri State": "St640",
  "Clayworks": "St149",
  "Club Baseball": "St618",
  "College Dems (MSU College Dems)": "St943",
  "College Republicans": "St100",
  "Colleges Against Cancer (Relay for Life)": "St128",
  "Collegiate Farm Bureau": "St151",
  "Collegiate FFA (FFA)": "St591",
  "Communication Sciences and Disorders, Department of": "De67",
  "Communication Services": "De68",
  "Communication Studies, School of": "De214",
  "Communication, Department of": "De66",
  "Community and Social Issues Institute": "De324",
  "Community Engagement, Center for": "Su1090",
  "Community Involvement and Service (formerly Volunteer Programs)": "De131",
  "Computer Information Systems Program, Master of Science in": "De266",
  "Computer Information Systems, Department of": "De69",
  "Computer Science, Department of": "De70",
  "Computer Services": "De33",
  "Computers for Learning Course": "Su497",
  "Concert Chorale": "Su730",
  "Concrete Consortium (MSU ACI)": "St981",
  "Conflict Resolution in College (CRC)": "St931",
  "Construction Club (AGC Construction Club)": "St38",
  "Counseling and Testing Center": "De73",
  "Counseling Outreach &amp; Peer Engagement (COPE)": "St870",
  "Counseling, Leadership and Special Education, Department of": "De345",
  "Criminal Justice Society": "St46",
  "Criminology and Criminal Justice Department": "De187",
  "Cross Bearers": "St197",
  "Cru": "St96",
  "Custodial Services": "De357",
  "Dance Bear-A-Thon (DBAT)": "St743",
  "Darr School of Agriculture, William H.": "De52",
  "Dean of Students Office": "De203",
  "Defense and Strategic Studies Department": "De74",
  "Delta Alpha Pi": "St814",
  "Delta Chi Fraternity (D Chi)": "St330",
  "Delta Sigma Pi": "St7",
  "Delta Sigma Theta Sorority, Inc. (DST, The Redz)": "St101",
  "Delta Tau Alpha (Agriculture Honor Society) (DTA)": "St205",
  "Delta Zeta Sorority (Dee Zee)": "St206",
  "Development and Alumni Relations": "De10",
  "Dietetics Program": "De227",
  "Dining Services": "De11",
  "Disability Resource Center": "De46",
  "Disability Studies Program": "De407",
  "Disc Golf Club": "St968",
  "Dispute Resolution, Center for": "De247",
  "Diversity and Inclusion, Office for": "De377",
  "Ducks Unlimited (MSU Ducks Unlimited)": "St1012",
  "Economic Research, Bureau of": "De336",
  "Economics Club (Econ Club)": "St152",
  "Economics Department": "De76",
  "Education, College of": "De15",
  "Educational Field Experiences": "De360",
  "Educational Technology Graduate Program": "De229",
  "Educator Preparation Provider": "De113",
  "eFactory": "De402",
  "Employee Wellness Program": "De349",
  "Enactus Missouri State University (Enactus)": "St21",
  "Engineering Program": "De361",
  "English Department": "De78",
  "English Language Institute": "De152",
  "English Society (Eng. Soc.)": "St896",
  "Enrollment Management and Services": "De79",
  "Entertainment Management": "Su252",
  "Entertainment Management Association (EMA)": "St120",
  "Entrepreneurship and Innovation Association (EIA)": "St578",
  "Environmental Management": "De232",
  "Environmental Sciences and Policy Program": "De189",
  "Essence of Hip Hop (Essence )": "St829",
  "Eta Sigma Delta": "St207",
  "Event and Meeting Services": "De192",
  "Exercise Science Association (ESA)": "St833",
  "EXIST": "St872",
  "Facilities Maintenance": "De356",
  "Facilities Management": "De109",
  "Faculty Center for Teaching and Learning": "De353",
  "Faculty Senate": "De134",
  "FAITH Ministries": "St873",
  "Family Association": "Su482",
  "Family Career and Community Leaders of America (FCCLA)": "St826",
  "Family Nurse Practitioner Student Association (FNPSA)": "St820",
  "Fashion and Interior Design, Department of": "De71",
  "Fellowship of Catholic University Students  (FOCUS )": "St874",
  "Fellowships Office": "De343",
  "Fencing Society": "St208",
  "Film Society (MSU Film Society)": "St1013",
  "Finance and General Business Department": "De81",
  "Financial Aid, Office of": "De126",
  "Financial Management Association (FMA)": "St74",
  "Financial Services": "De82",
  "First &amp; Calvary Presbyterian Church Campus Ministry (FnC)": "St209",
  "First-Year Programs": "De72",
  "Fishing Team (MSU Fishing Team)": "St830",
  "Flute Society": "St154",
  "Folklore Club": "St756",
  "Foreign Language Institute": "De395",
  "Foster Recreation Center Association (FRC Association)": "St982",
  "Fraternity &amp; Sorority Life Leaders of Social Awarness (FSLSA)": "St1026",
  "Fraternity and Sorority Life": "De191",
  "Freethinkers &amp; Skeptics at Missouri State University (FSMSU)": "St932",
  "Freudenberger House (Freddy)": "St921",
  "Fusion Dance Production (FDP)": "St897",
  "Future Engineers &amp; Renewable Energy (FE &amp; RE)": "St971",
  "Future Public Health Professionals (FPHP)": "St751",
  "Gaming Club of Missouri State University (Gaming Club)": "St933",
  "Gamma Alpha Lambda (GAL)": "St525",
  "Gamma Iota Sigma (GIS)": "St114",
  "Gamma Phi Beta (G Phi)": "St844",
  "Gamma Pi Alpha (GPA)": "St71",
  "Gamma Sigma Sigma": "St54",
  "Gamma Theta Upsilon/Geography Club (GTU/Geography Club)": "St934",
  "Gender Studies Program": "De85",
  "General Counsel's Office": "De410",
  "Geography, Geology, and Planning Department": "De86",
  "Geological Society": "St83",
  "German Club": "St972",
  "Gerontology Club (GER Club)": "St156",
  "Global Engagement Corps (GEC)": "St889",
  "GO LEAD: Professional Development for the Nonprofit Sector": "Su925",
  "God's Chosen Ministry (God's Chosen; GC)": "St983",
  "Golden Key International Honour Society (GK)": "St41",
  "Graduate College": "De87",
  "Graduate of Business Professional Honor Society": "St42",
  "Graduate Student Senate (GSS)": "St64",
  "Grapevine Biotechnology, Center for (CGB)": "De338",
  "Green Room, The (Green Room)": "St875",
  "Greenwood Laboratory School": "De88",
  "Grounds Department": "De184",
  "Habitat for Humanity": "St80",
  "Hammons Hall Council  (Hammons House Hall Council)": "St212",
  "Hammons House": "St922",
  "Hammons Student Center": "De158",
  "Handball Team (MSU Handball Team)": "St43",
  "Hats for Healing": "St959",
  "Health and Human Services, College of": "De16",
  "Health Services Association": "St1014",
  "Healthcare Plans Review Committee": "Su564",
  "Hibernotes": "St953",
  "Hillel of Southwest Missouri (Hillel)": "St960",
  "History Department": "De90",
  "Home Builders Organization (MSHBO)": "St984",
  "Homeland Security, Center for": "De355",
  "Honors College": "De91",
  "Honors Council": "St323",
  "Horsemen's Association (Horsemen's)": "St106",
  "Horticulture Club": "St157",
  "Hospitality and Restaurant Administration Department": "De348",
  "Hospitality Leaders of Tomorrow (HLOT)": "St158",
  "Human Resources, Office of": "De92",
  "Humanist Association (MSHA)": "St941",
  "Humanities and Public Affairs, College of": "De17",
  "Hutchens House": "St923",
  "Ice Girls": "St741",
  "Ice Hockey Club": "St112",
  "ICTHUS": "St11",
  "IEEE Student Branch of Missouri State University (MSU IEEE)": "St935",
  "Ignite Christan Ministies (LJC Ignite )": "St1015",
  "Improv (Missouri State Improv)": "St1016",
  "Indian Students Association (Indian Students Association - ISA)": "St865",
  "Industrial Productivity, Center for": "De340",
  "Industrial/Organizational Psychology Club (I-O Club)": "St217",
  "Information Desk": "Su130",
  "Institutional Equity and Compliance, Office for": "De175",
  "Institutional Research, Office of": "De154",
  "Inter-Fraternity Council (IFC)": "St75",
  "Internal Audit and Compliance, Office of": "De204",
  "International Business Programs": "De48",
  "International City/County Management Association (ICMA Student Chapter of MSU)": "St1017",
  "International Facilities Managment Association at Missouri State  (IFMA)": "St937",
  "International Justice Mission Campus Chapter (IJM CC)": "St1027",
  "International Leadership and Training Center": "De405",
  "International Programs": "De328",
  "International Public Affairs Leaders (iPALs)": "St916",
  "International Services": "De94",
  "Intramural Sports": "De327",
  "Iota Tau Alpha Athletic Training Education Honor Society (Iota Tau Alpha)": "St731",
  "James River Basin Partnership": "De350",
  "Japanese Animation Club": "St327",
  "Jewelry Students Association (JSA)": "St221",
  "JQH Arena": "De320",
  "Juanita K. Hammons Hall for the Performing Arts": "De199",
  "Judo and Jujitsu Club": "St1018",
  "Kappa Alpha Order (KA)": "St223",
  "Kappa Alpha Psi": "St6",
  "Kappa Delta Pi": "St224",
  "Kappa Kappa Psi": "St527",
  "Kappa Mu Epsilon (KME)": "St226",
  "Kappa Sigma (Kappa Sig)": "St12",
  "Kentwood Hall  (Kentwood)": "St924",
  "Kinesiology Department": "De89",
  "Korean Bears (KB)": "St973",
  "KSMU Radio Station": "De95",
  "Lacrosse Club": "St236",
  "Lambda Chi Alpha Fraternity (Lambda Chi)": "St1019",
  "Lambda Pi Eta (LPH)": "St231",
  "Latin American Studies Program": "De268",
  "Latter-Day Saints Student Association (LDSSA)": "St232",
  "Le Club Français (Les Francophones)": "St900",
  "Leaders in Community Service (LCS)": "St110",
  "Leading in Education to Approach Latinos (L.E.A.L.)": "St736",
  "Learning Diagnostic Clinic": "De96",
  "Leisure Research, Office of": "De2",
  "LGBT Association": "Un2",
  "Libraries": "De97",
  "Library Science Department": "De6",
  "Lifestyle": "St901",
  "Linguistics Program": "Su559",
  "Linked": "St985",
  "Live Action Society of Missouri State University (LAS)": "St835",
  "Logistics And Supply Chain Management Association (LSCMA)": "St767",
  "Lutheran Student Center (LSC)": "St13",
  "Management Department": "De98",
  "Management Development Institute": "De99",
  "Marketing and Communications, Division of": "De197",
  "Marketing and Promotions, Missouri State Outreach": "De330",
  "Marketing Club (MSU Marketing Club)": "St317",
  "Marketing Department": "De101",
  "Maroon Madness": "St702",
  "Mathematical Association of America (MAA)": "St534",
  "Mathematics Department": "De100",
  "MBA Association (MBAA)": "St938",
  "Media, Journalism &amp; Film, Department of": "De198",
  "Medical Reserve Corps at Missouri State University (MRC @ MSU)": "St939",
  "Men's Ultimate (Missouri State Men's Ultimate)": "St119",
  "Middle Eastern Studies Program": "De230",
  "Military Science Department": "De102",
  "Missouri Association of Planning Students (MAPS)": "St239",
  "Missouri Campus Compact": "Su458",
  "Missouri Public Affairs Academy": "Su202",
  "Missouri State Online": "De208",
  "Missouri State Outreach": "De362",
  "Missouri State University Foundation": "De116",
  "Missouri State University Pageant Association (MSU Pageant Association)": "St986",
  "MO State Movement": "St944",
  "Model United Nations (MUN)": "St987",
  "Modern and Classical Languages Department": "De83",
  "Moon City Press": "Su1033",
  "Motorcycle Club (MC)": "St1020",
  "Mountain Grove Campus": "De23",
  "Mu Phi Epsilon": "St335",
  "Multicultural Programs": "Su724",
  "Multicultural Services, Office of": "De104",
  "Music and Entertainment Industry Student Association (MEISA)": "St810",
  "Music Department": "De105",
  "NAMI on Campus": "St988",
  "Nat. Society of Professional Engineers (NSPE)": "St1021",
  "National Art Education Association (NAEA)": "St336",
  "National Association for Music Education - Collegiate (NAfME-C)": "St989",
  "National Pan-Hellenic Council (NPHC)": "St241",
  "National Residence Hall Honorary": "St242",
  "National Society of Collegiate Scholars (NSCS)": "St243",
  "National Student Speech Language Hearing Association (NSSLHA)": "St121",
  "Native American Studies Program": "De231",
  "Natural and Applied Science, Master of": "De188",
  "Natural and Applied Sciences, College of": "De18",
  "Natural History Collection Curation Club (NHC3)": "St1022",
  "Noncredit, Missouri State Outreach": "De383",
  "Nursing Department": "De128",
  "Opal Agency": "St963",
  "Order of Harmony, The (OoH)": "St975",
  "Order of Omega": "St250",
  "Outdoor Adventures": "De219",
  "Ozarks Amateur Astronomers Club": "St252",
  "Ozarks Biological Graduate Society (OBGS)": "St160",
  "Ozarks Environmental and Water Resources Institute (OEWRI)": "De339",
  "Ozarks Public Health Institute": "De211",
  "Ozarks Public Television": "De200",
  "Ozarks Student Chapter, National Association of Teachers of Singing (SNATS)": "St990",
  "Ozarks Studies Institute": "De149",
  "Ozarks Studies Program": "De374",
  "Ozarks Writing Project": "Su833",
  "Panhellenic Association (PHA)": "St66",
  "Peer Leader Association (PLA)": "St946",
  "Percussion Society (MSUPS)": "St162",
  "Pershing Rifles L-2 Company (L-2 Company)": "St1023",
  "Phi Alpha Delta Pre-Law Fraternity": "St5",
  "Phi Alpha Theta": "St255",
  "Phi Beta Lambda (PBL)": "St974",
  "Phi Beta Sigma Fraternity, Inc. (Rho Chi Chapter) (The Sigmas)": "St67",
  "Phi Delta Theta (Phi Delt)": "St15",
  "Phi Eta Sigma": "St51",
  "Phi Gamma Delta (FIJI)": "St742",
  "Phi Mu Alpha Sinfonia": "St16",
  "Phi Sigma Pi": "St9",
  "Phi Sigma Upsilon (Phi Sig)": "St878",
  "Philosophy Club": "St163",
  "Philosophy Department": "De108",
  "Photographic Services": "De155",
  "Physical Education Majors Club": "St164",
  "Physical Therapy Clinic": "De277",
  "Physical Therapy Department": "De38",
  "Physician Assistant Student Society of Missouri State University": "St917",
  "Physician Assistant Studies Department": "De150",
  "Physics, Astronomy and Materials Science": "De148",
  "Pi Kappa Alpha Fraternity (PIKE)": "St902",
  "Pi Kappa Phi Fraternity (Pi Kapp)": "St639",
  "Planning, Design and Construction, Office of": "De40",
  "Plaster Stadium, Robert W.": "De228",
  "Plaster Student Union": "De185",
  "Political Science Department": "De111",
  "Political Science Graduate Student Association (PSGSA)": "St903",
  "Postal Services": "De28",
  "Potter's House": "St760",
  "Pre-Dental Society": "St879",
  "Pre-Medical Society": "St47",
  "Pre-Occupational Therapy Club": "St880",
  "Pre-Optometry Club (Pre-Opt Club)": "St262",
  "Pre-Pharmacy Society": "St828",
  "Pre-Physical Therapy Student Association (PPTSA or Pre-PT Association)": "St779",
  "Pre-Physician Assistant Society (PPAS)": "St696",
  "Pre-Veterinary Club (Pre-Vet Club)": "St143",
  "President, Office of the": "De29",
  "Printing Services": "De30",
  "Procurement Services": "De144",
  "Professional Education Advisement Center": "De205",
  "Project ACCESS": "De202",
  "Project Innovation and Management Education (C-PRIME), Center for": "De369",
  "Property Control": "De114",
  "Provost, Office of": "De49",
  "Psi Chi": "St263",
  "Psychology Club": "St165",
  "Psychology Department": "De112",
  "Public Affairs Mission": "De13",
  "Public Health, Master of": "De352",
  "Public Relations Student Society of America (PRSSA)": "St720",
  "Publications, Office of": "De196",
  "Ranch Horse Team": "St905",
  "Ranger Challenge Club (RC)": "St954",
  "Reading, Foundations, and Technology, Department of (RFT)": "De344",
  "Recreational Outdoors Club (ROC)": "St55",
  "Recruiting Emerging Alumni Leaders Bears (R.E.A.L. Bears)": "St321",
  "Reference and Government Information Department": "De342",
  "Regional Professional Development Center, Southwest": "De115",
  "Registrar, Office of the": "De37",
  "Registration Services, Missouri State Outreach": "De331",
  "Religious Studies Club, The": "St356",
  "Religious Studies Department": "De8",
  "Research Administration, Office of": "Su1075",
  "Research and Economic Development": "De278",
  "Research Compliance, Office of": "Su922",
  "Residence Hall Association (RHA)": "St4",
  "Residence Life, Housing and Dining Services": "De7",
  "Resource Planning and Management, Center for": "De63",
  "Reverb": "St906",
  "Rho Lambda": "St735",
  "Rifle Team": "St853",
  "Roller Derby Club. ": "St947",
  "Roller Hockey Club": "St111",
  "ROTC (Reserve Officers' Training Corps)": "Su24",
  "RStats (Research, Statistical Training and Technical Support)": "De387",
  "Running Club, The": "St658",
  "Safety and Transportation, Department of": "De4",
  "Saudi Club of MSU": "St907",
  "Saxophone Society": "St268",
  "Scholars House": "St655",
  "School Improvement, Institute for": "De157",
  "Secondary Education": "De382",
  "Sigma Alpha": "St271",
  "Sigma Chi Fraternity (Sigma Chi)": "St908",
  "Sigma Kappa": "St273",
  "Sigma Lamda Chi Upsilon IV (SLX)": "St1024",
  "Sigma Nu Fraternity (Sigma Nu)": "St848",
  "Sigma Phi Epsilon (Sig Ep)": "St102",
  "Sigma Pi Fraternity (Sigma Pi)": "St964",
  "Sigma Sigma Sigma (Tri Sigma)": "St991",
  "Sigma Tau Delta": "St338",
  "Sign Language Club (SLC)": "St992",
  "Sister Circle": "St276",
  "Small Business and Technology Development Center (SBTDC)": "De36",
  "SOAR": "De43",
  "SoBEAR": "Su1093",
  "Soccer Club (Club Soccer Team)": "St1003",
  "Social Sciences and Public Policy Research, Center for": "De1",
  "Social Work Club (BSWSA)": "St857",
  "Social Work, School of": "De117",
  "Society for Human Resource Management": "St279",
  "Society for Technical Communication": "St19",
  "Society of Manufacturing Engineers (SME)": "St56",
  "Society of Physics Students": "St167",
  "Sociology and Anthropology Department": "De118",
  "Sociology Organization (Soc Club)": "St948",
  "Space Management": "De39",
  "Spanish Club (The Spanish Club)": "St909",
  "Spectrum": "St882",
  "Speech-Language and Hearing Clinic": "De194",
  "Spirit Squads": "Su783",
  "Sports Medicine and Athletic Training Department": "De119",
  "Springfield Design Association (SDA)": "St1025",
  "Springfield Innovation, Inc.": "De347",
  "St. Baldrick's - MSU Chapter": "St1028",
  "Staff Senate": "De120",
  "Standard, The": "Su44",
  "Student Academic Support Services": "De19",
  "Student Academy of Audiology (SAA)": "St326",
  "Student Activities Council (SAC)": "St72",
  "Student Affairs, Division of": "De21",
  "Student Athlete Advisory Committee (SAAC)": "St282",
  "Student Conduct, Office of": "De195",
  "Student Council for Exceptional Children (SCEC)": "St68",
  "Student Development and Public Affairs": "De124",
  "Student Dietetic Association (SDA )": "St40",
  "Student Employment Services": "De27",
  "Student Engagement, Office of": "De201",
  "Student Government Association (SGA)": "St50",
  "Student Library Science Association  (SLSA)": "St910",
  "Student Math Teacher Organization of Southwest Missouri ((SM)^2TO)": "St339",
  "Student Missouri State Teacher Association (SMSTA)": "St20",
  "Student Mobilization (StuMo)": "St950",
  "Student National Education Association (SNEA)": "St284",
  "Student Nurse Organization (SNO)": "St689",
  "Student Photographic Society (Photo Society)": "St285",
  "Student Speech and Theatre Association of Missouri at Missouri State University (Stud": "St911",
  "Students athletes of Color Combining Opportunities to Reach Excellence (SCORE)": "St993",
  "Students for a Sustainable Future (SSF)": "St744",
  "Students for Sensible Drug Policy (SSDP)": "St994",
  "Students in Design (SiD)": "St613",
  "Students Today, Leaders Forever (STLF)": "St1002",
  "Students United for Nutrition (SUN)": "St1029",
  "Study Away Programs": "De121",
  "Sugar Bears Dance Team": "De248",
  "Sunvilla Tower (Sunvilla)": "St925",
  "Sustainability": "Su840",
  "Swing Club (MoState Lindy Hoppers)": "St995",
  "Tabula Rasa Theatre Production Company (Tabula Rasa)": "St996",
  "Taiwanese Student Association": "St712",
  "Tau Kappa Epsilon (TKE/Tekes)": "St791",
  "Taylor Health and Wellness Center": "De9",
  "Teacher Certification Office": "De213",
  "Technology and Construction Management, Department of": "De122",
  "Tennis Club": "St884",
  "Theatre and Dance Department": "De123",
  "Theta Alpha Kappa (TAK)": "St341",
  "Theta Chi Fraternity (Theta Chi)": "St82",
  "Tibbers (Team Tibbers)": "St997",
  "TOMS Initiative  (TOMS Club)": "St969",
  "Trap &amp; Skeet Team": "St290",
  "Triathlon Club (MSU Triathlon Club/Multi-sport)": "St942",
  "TRIO: Student Support Services": "De125",
  "TRIO: Upward Bound Program": "Su557",
  "Trixie Chicks Trick Riders Association": "St976",
  "Unifying Negroes Intellectually Through Empowerment (U.N.I.T.E.)": "St57",
  "UNITED": "St999",
  "United Ministries in Higher Education": "St3",
  "United Students for Fair Trade": "St773",
  "University Advancement Division": "De141",
  "University Ambassadors (UA)": "St52",
  "University Child Care Center": "De223",
  "University Coalition of Young Artists  (UCYA)": "St965",
  "University Communications, Office of": "De106",
  "Untamed Tongues ": "St1030",
  "Vertical Access (VA)": "St237",
  "Veteran Student Services": "Su802",
  "Veterans Student Organization (VSO)": "St919",
  "Vine, The": "St585",
  "Vineyard, The": "St852",
  "Violin Society (MSU Violin Society)": "St1000",
  "Virtual Language Center": "De42",
  "VOX (Voices for Planned Parenthood)": "St843",
  "Water Ski Club": "St328",
  "Web and New Media, Office of": "De276",
  "Wells House": "St926",
  "West Plains Campus": "De22",
  "Wildlife Society of MSU": "St296",
  "Women's Lacrosse Team (Women's Lacrosse)": "St913",
  "Women's Ultimate Frisbee Team (Women's Ultimate)": "St885",
  "Woods House": "St927",
  "Work Management Center": "De183",
  "Wrestling Club": "St918",
  "Writing Center": "De32",
  "Xi Omicron Iota (XI OM)": "St298",
  "Young Life Crew": "St682",
  "Zeta Phi Beta Sorority, Incorporated": "St732"
}
tests = {
  "fsl":/\b(phi|alpha|psi|gamma|pi|xi|zeta|sigma|sorority|fraternity|fsl)\b/i
  "interest":/club|association|organization|society/i
  "academic":/\w+ology\b|college of|academ\w+/i
  "house":/house|tower|blair/i
  "campus":/campus|missouri|office|university|center/i
  "sport":/team|game|hockey|basketball|frisbee|league|football/i
}

object = {other:[]}

for cat of tests
  object[cat] = []

for name, value of r
  found = false
  for cat, test_re of tests
    if test_re.test name
      object[cat].push [name, value]
      found = true
  if not found
    object.other.push [name, value]

Say JSON.stringify object, null, 2
